application: lumivote
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img

- url: /pages
  static_dir: pages

- url: /api/.*
  script: api/api.php

- url: /api2/.*
  script: api2/index.php

- url: .*
  script: index.html
