application: lumivote
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /pages
  static_dir: pages

- url: /api/.*
  script: api/api.php

- url: /app/candidates
  script: app/candidates/home.html

- url: /app/timeline
  script: app/timeline/home.html

- url: /app/candidates/.*
  script: app/candidates/api/api.php

- url: /app/timeline/.*
  script: app/timeline/api/api.php

- url: .*
  script: index.html
